backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
media_folder: "_assets/img/content" # Media files will be stored in the repo under images/uploads
public_folder: "assets/img/content"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - label: "Featured Image"
        name: "image"
        widget: "image"
        pattern: ['^.*\.(jpg|jpeg|JPG|JPEG)$', "Extension must be jpg"]
        comment: 'Extension must be jpg'
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", comment: 'should be comma separated'}
      - {label: "Table of contents", name: "toc", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}