backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
media_folder: "_assets/img/content" # Media files will be stored in the repo under images/uploads
public_folder: "/assets/img/content"

publish_mode: editorial_workflow

locale: 'tr'

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    description: >
      Medyanot blog yazıları burada toplanıyor.
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    summary: '{{title}}   {{day}}{{month}}{{year}}'
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Drafts
        field: draft
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", hint: "Yazı başlığı"}
      - label: "Featured Image"
        name: "image"
        required: true
        widget: "image"
        pattern: ['^.*\.(jpg|jpeg|JPG|JPEG)$', "Image file extension must be jpg"]
        hint: 'jpg uzantılı bir görsel seçilmeli. Görsel "xxx-featured.jpg" olarak adlandırılmalı. Yatay görseller daha iyi görünür.'
      - {label: "Description", name: "description", widget: "string", hint: "Yazı özeti"}
      - {label: "Tags", name: "tags", widget: "list", hint: 'Etiketler virgülle ayrılmalı'}
      - {label: "Table of contents", name: "toc", widget: "boolean", default: false, hint: "H2 ara başlıklarını kullanarak oluşturulan içindekiler bölümü"}
      - {label: "Draft", name: "draft", widget: "boolean", hint: "Açık olması henüz taslak halinde olduğunu gösterir.", default: true}
      - {label: "Body", name: "body", widget: "markdown", hint: "Uyarı- Body kısmına eklenen görsellerde Title kısmı boş bırakılmalı"}
  - name: "pages"
    label: "Page"
    folder: "_pages"
    description: >
      Medyanot'un sabit sayfaları burada toplanıyor.
    create: true
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}